language: python
python: 3.7

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten emcmake cmake .
  - docker exec -it emscripten make
  - mkdir html && mv index.html style.css *.js *.wasm html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: html
